[build]
builder = "nixpacks"
buildCommand = "npm ci && pip install -r requirements.txt"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
python = { version = "3.10" }
node = { version = "18" }

[variables]
PORT = "8000"
ENVIRONMENT = "production"
